version: '3.7'

services:
  
  consul-server1:
    image: consul:1.13.2
    container_name: server1
#    restart: always
    environment:
      CONSUL_HTTP_ADDR: "server1:8500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    volumes:
     - ./server1.hcl:/consul/config/server1.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
     - ./redis.json:/consul/config/redis.json
     - ./redis-cli:/bin/redis-cli
    networks:
      consul:
        ipv4_address: 10.10.10.2
    ports:
      - "8500:8500"
      - "8501:8501"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: consul:1.13.2
    container_name: server2
#    restart: always
    environment:
      CONSUL_HTTP_ADDR: "server2:18500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    volumes:
     - ./server2.hcl:/consul/config/server2.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
    networks:
      consul:
        ipv4_address: 10.10.10.3
    ports:
      - "18302:8302/tcp"
      - "18301:8301/udp"
      - "18300:8300/tcp"
      - "18500:8500"
      - "18501:8501"
      - "18600:8600/tcp"
      - "18600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: consul:1.13.2
    container_name: server3
#    restart: always
    environment:
      CONSUL_HTTP_ADDR: "server3:19500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    volumes:
     - ./server3.hcl:/consul/config/server3.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
    networks:
      consul:
        ipv4_address: 10.10.10.4
    ports:
      - "19302:8302/tcp"
      - "19301:8301/udp"
      - "19300:8300/tcp"
      - "19500:8500"
      - "19501:19501"
      - "19600:8600/tcp"
      - "19600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-client1:
    image: consul:1.13.2
    container_name: client1
#    restart: always
    volumes:
     - ./client1.hcl:/consul/config/client1.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
    networks:
      consul:
        ipv4_address: 10.10.10.5
    command: "agent"
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    networks:
      consul:
        ipv4_address: 10.10.10.6
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  redis1:
    image: redis:6.2-alpine
    container_name: redis1
    restart: always
    networks:
      consul:
        ipv4_address: 10.10.10.7
    ports:
      - '6389:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data1
  dashboard:
    container_name: dashboard
    hostname: dashboard
    image: 'hashicorp/dashboard-service:0.0.4'
    restart: always
    ports:
      - '9002:9002'
    environment:
      PORT: 9002
      COUNTING_SERVICE_URL: 'http://counting-service:9002'
    depends_on:
      - counting-service
    networks:
      consul:
        ipv4_address: 10.10.10.8

  counting-service:
    container_name: counting-service
    hostname: counting-service
    image: 'hashicorp/counting-service:0.0.2'
    restart: always
    ports:
      - '9001:9001'
    environment:
      PORT: 9001
    networks:
      consul:
        ipv4_address: 10.10.10.9
  dashboard1:
    container_name: dashboard1
    hostname: dashboard1
    image: 'hashicorp/dashboard-service:0.0.4'
    restart: always
    ports:
      - '9004:9004'
    environment:
      PORT: 9004
      COUNTING_SERVICE_URL: 'http://counting-service:9004'
    depends_on:
      - counting-service
    networks:
      consul:
        ipv4_address: 10.10.10.10

  counting-service1:
    container_name: counting-service1
    hostname: counting-service1
    image: 'hashicorp/counting-service:0.0.2'
    restart: always
    ports:
      - '9003:9003'
    environment:
      PORT: 9003
    networks:
      consul:
        ipv4_address: 10.10.10.11
  dashboard-client:
    container_name: dashboard-client
    hostname: dashboard-client
    image: 'hashicorp/dashboard-service:0.0.4'
    restart: always
    ports:
      - '9006:9006'
    environment:
      PORT: 9006
      COUNTING_SERVICE_URL: 'http://counting-service:9006'
    depends_on:
      - counting-service
    networks:
      consul:
        ipv4_address: 10.10.10.12
  counting-client1:
    container_name: counting-client
    hostname: counting-client
    image: 'hashicorp/counting-service:0.0.2'
    restart: always
    ports:
      - '9005:9005'
    environment:
      PORT: 9005
    networks:
      consul:
        ipv4_address: 10.10.10.13
volumes:
  cache:
    driver: local


networks:
  consul:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
          gateway: "10.10.10.1"