version: '3.7'

services:
  
  consul-server1:
    image: consul:1.13.2
    container_name: consul-server1
#    restart: always
    environment:
      CONSUL_HTTP_ADDR: "consul-server1:8500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    volumes:
     - ./server1.hcl:/consul/config/server1.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
     - ./redis.json:/consul/config/redis.json
     - ./redis-cli:/bin/redis-cli
    networks:
      consul:
        ipv4_address: 10.10.10.2
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: consul:1.13.2
    container_name: consul-server2
#    restart: always
    environment:
      CONSUL_HTTP_ADDR: "consul-server2:18500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    volumes:
     - ./server2.hcl:/consul/config/server2.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
    networks:
      consul:
        ipv4_address: 10.10.10.3
    ports:
      - "18302:8302/tcp"
      - "18301:8301/udp"
      - "18300:8300/tcp"
      - "18500:8500"
      - "18600:8600/tcp"
      - "18600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: consul:1.13.2
    container_name: consul-server3
#    restart: always
    environment:
      CONSUL_HTTP_ADDR: "consul-server3:19500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    volumes:
     - ./server3.hcl:/consul/config/server3.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
    networks:
      consul:
        ipv4_address: 10.10.10.4
    ports:
      - "19302:8302/tcp"
      - "19301:8301/udp"
      - "19300:8300/tcp"
      - "19500:8500"
      - "19600:8600/tcp"
      - "19600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-client1:
    image: consul:1.13.2
    container_name: consul-client1
#    restart: always
    volumes:
     - ./client1.hcl:/consul/config/client1.hcl
     - ./acls/:/consul/config/acls/
     - ./certs/:/consul/config/certs/
    networks:
      consul:
        ipv4_address: 10.10.10.5
    command: "agent"
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    networks:
      consul:
        ipv4_address: 10.10.10.6
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local


networks:
  consul:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
          gateway: "10.10.10.1"